#!/usr/bin/env Rscript
source("~/projecto/research_projects/poker_information/info_decomp_fns005.r")

reps <- 500
#increment_me <- "040_unordered"
#increment_me <- "040_showdown_ordered_preflop"
increment_me <- "040"

path_poker <- "~/projecto/research_projects/poker_information/"
#file_ABS_1000 <- paste(path_poker, "poker_distributions_2p_ABS_1000_", increment_me, ".Rdata", sep='')
#file_ABS_0600 <- paste(path_poker, "poker_distributions_2p_ABS_0600_", increment_me, ".Rdata", sep='')
#file_ABS_0400 <- paste(path_poker, "poker_distributions_2p_ABS_0400_", increment_me, ".Rdata", sep='')
#file_ABS_0200 <- paste(path_poker, "poker_distributions_2p_ABS_0200_", increment_me, ".Rdata", sep='')
#file_ABS_0100 <- paste(path_poker, "poker_distributions_2p_ABS_0100_", increment_me, ".Rdata", sep='')
#file_ABS_0050 <- paste(path_poker, "poker_distributions_2p_ABS_0050_", increment_me, ".Rdata", sep='')
file_PS_1000 <- paste(path_poker, "poker_distributions_2p_PS_1000_", increment_me, ".Rdata", sep='')
file_PS_0600 <- paste(path_poker, "poker_distributions_2p_PS_0600_", increment_me, ".Rdata", sep='')
file_PS_0400 <- paste(path_poker, "poker_distributions_2p_PS_0400_", increment_me, ".Rdata", sep='')
file_PS_0200 <- paste(path_poker, "poker_distributions_2p_PS_0200_", increment_me, ".Rdata", sep='')
file_PS_0100 <- paste(path_poker, "poker_distributions_2p_PS_0100_", increment_me, ".Rdata", sep='')
file_PS_0050 <- paste(path_poker, "poker_distributions_2p_PS_0050_", increment_me, ".Rdata", sep='')
file_PS_0025 <- paste(path_poker, "poker_distributions_2p_PS_0025_", increment_me, ".Rdata", sep='')

#print("ABS 1000")
#bootstrap_distributions_to_file(paste(path_poker, "distrABS100.csv", sep=''), reps, file_ABS_1000)
#print("ABS 0600")
#bootstrap_distributions_to_file(paste(path_poker, "distrABS060.csv", sep=''), reps, file_ABS_0600)
#print("ABS 0400")
#bootstrap_distributions_to_file(paste(path_poker, "distrABS040.csv", sep=''), reps, file_ABS_0400)
#print("ABS 0200")
#bootstrap_distributions_to_file(paste(path_poker, "distrABS020.csv", sep=''), reps, file_ABS_0200)
#print("ABS 0100")
#bootstrap_distributions_to_file(paste(path_poker, "distrABS010.csv", sep=''), reps, file_ABS_0100)
#print("ABS 0050")
#bootstrap_distributions_to_file(paste(path_poker, "distrABS005.csv", sep=''), reps, file_ABS_0050)
print("PS 1000")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS1000_3.csv", file_PS_1000, reps, ordered=T)
print("PS 0025")  ### it's really big, so I may crash, and if I'm gonna crash I want to crash early
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS0025_4.csv", file_PS_0025, reps, ordered=T)
print("PS 0600")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS0600_3.csv", file_PS_0600, reps, ordered=T)
print("PS 0400")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS0400_3.csv", file_PS_0400, reps, ordered=T)
print("PS 0200")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS0200_3.csv", file_PS_0200, reps, ordered=T)
print("PS 0100")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS0100_3.csv", file_PS_0100, reps, ordered=T)
print("PS 0050")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS0050_3.csv", file_PS_0050, reps, ordered=T)

print("long form"); Sys.time()
stat_long_2p <- rbind(
  #cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_1000,specific=NA)),blind=10.00,ublind="ABS10.00", site="ABS", specific=NA)
  #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0600,specific=NA)),blind=6.00, ublind="ABS6.00", site="ABS", specific=NA)
  #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0400,specific=NA)),blind=4.00, ublind="ABS4.00", site="ABS", specific=NA)
  #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0200,specific=NA)),blind=2.00, ublind="ABS2.00", site="ABS", specific=NA)
  #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0100,specific=NA)),blind=1.00, ublind="ABS1.00", site="ABS", specific=NA)
  #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0050,specific=NA)),blind=0.50, ublind="ABS0.50", site="ABS", specific=NA)
  cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_1000,specific=NA)), blind=10.00, ublind="PS10.00", site="PS", specific=NA)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0600, specific=NA)), blind=6.00, ublind="PS6.00", site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0400, specific=NA)), blind=4.00, ublind="PS4.00", site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0200, specific=NA)), blind=2.00, ublind="PS2.00", site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0100, specific=NA)), blind=1.00, ublind="PS1.00", site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0050, specific=NA)), blind=0.50, ublind="PS0.50", site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0025, specific=NA)), blind=0.25, ublind="PS0.25", site="PS", specific=NA)
                                )
stat_long_2p_spec <- rbind(
#cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_1000, specific=1)), blind=10.00, ublind="ABS10.00", site="ABS", specific=1)
#,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_1000,specific=2)), blind=10.00, ublind="ABS10.00", site="ABS", specific=2)
#,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_1000,specific=3)), blind=10.00, ublind="ABS10.00", site="ABS", specific=3)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0600, specific=1)), blind=6.00, ublind="ABS6.00", site="ABS", specific=1)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0600, specific=2)), blind=6.00, ublind="ABS6.00", site="ABS", specific=2)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0600, specific=3)), blind=6.00, ublind="ABS6.00", site="ABS", specific=3)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0400, specific=1)), blind=4.00, ublind="ABS4.00", site="ABS", specific=1)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0400, specific=2)), blind=4.00, ublind="ABS4.00", site="ABS", specific=2)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0400, specific=3)), blind=4.00, ublind="ABS4.00", site="ABS", specific=3)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0200, specific=1)), blind=2.00, ublind="ABS2.00", site="ABS", specific=1)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0200, specific=2)), blind=2.00, ublind="ABS2.00", site="ABS", specific=2)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0200, specific=3)), blind=2.00, ublind="ABS2.00", site="ABS", specific=3)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0100, specific=1)), blind=1.00, ublind="ABS1.00", site="ABS", specific=1)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0100, specific=2)), blind=1.00, ublind="ABS1.00", site="ABS", specific=2)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0100, specific=3)), blind=1.00, ublind="ABS1.00", site="ABS", specific=3)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0050, specific=1)), blind=0.50, ublind="ABS0.50", site="ABS", specific=1)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0050, specific=2)), blind=0.50, ublind="ABS0.50", site="ABS", specific=2)
 #,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0050, specific=3)), blind=0.50, ublind="ABS0.50", site="ABS", specific=3)
  cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_1000, specific=1)), blind=10.00, ublind="PS10.00", site="PS", specific=1)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_1000, specific=2)), blind=10.00, ublind="PS10.00", site="PS", specific=2)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_1000, specific=3)), blind=10.00, ublind="PS10.00", site="PS", specific=3)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0600, specific=1 )), blind=6.00, ublind="PS6.00", site="PS", specific=1)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0600, specific=2 )), blind=6.00, ublind="PS6.00", site="PS", specific=2)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0600, specific=3 )), blind=6.00, ublind="PS6.00", site="PS", specific=3)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0400, specific=1 )), blind=4.00, ublind="PS4.00", site="PS", specific=1)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0400, specific=2 )), blind=4.00, ublind="PS4.00", site="PS", specific=2)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0400, specific=3 )), blind=4.00, ublind="PS4.00", site="PS", specific=3)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0200, specific=1 )), blind=2.00, ublind="PS2.00", site="PS", specific=1) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0200, specific=2 )), blind=2.00, ublind="PS2.00", site="PS", specific=2) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0200, specific=3 )), blind=2.00, ublind="PS2.00", site="PS", specific=3) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0100, specific=1 )), blind=1.00, ublind="PS1.00", site="PS", specific=1) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0100, specific=2 )), blind=1.00, ublind="PS1.00", site="PS", specific=2) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0100, specific=3 )), blind=1.00, ublind="PS1.00", site="PS", specific=3) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0050, specific=1 )), blind=0.50, ublind="PS0.50", site="PS", specific=1) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0050, specific=2 )), blind=0.50, ublind="PS0.50", site="PS", specific=2) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0050, specific=3 )), blind=0.50, ublind="PS0.50", site="PS", specific=3) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0025, specific=1 )), blind=0.25, ublind="PS0.25", site="PS", specific=1) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0025, specific=2 )), blind=0.25, ublind="PS0.25", site="PS", specific=2) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0025, specific=3 )), blind=0.25, ublind="PS0.25", site="PS", specific=3) 
                                )
stat_long_2p_spec <- stat_long_spec_normalized_patch(stat_long_2p_spec, skip=TRUE)  ### I no longer need to normalize ever beause I'm not plotting perentages but raw information in bits. duh.

#increment_me <- "040_showdown"
#increment_me <- "040_preflop"
#increment_me <- "040_unordered"
#increment_me <- "040"
save(list=c("stat_long_2p", "stat_long_2p_spec"), file=paste("~/projecto/research_projects/poker_information/poker_graph_ready_data_", increment_me, ".Rdata", sep=''))

if (0 == "i want to calculate by street, but this hasn't been updated") {
  increment_me <- "040street"
  PS_all <- rbind(
                    read.csv("~/projecto_staid/poker_information/distrPS1000_2.csv")
                  , read.csv("~/projecto_staid/poker_information/distrPS0600_2.csv")
                  , read.csv("~/projecto_staid/poker_information/distrPS0400_2.csv")
                  , read.csv("~/projecto_staid/poker_information/distrPS0200_2.csv")
                  , read.csv("~/projecto_staid/poker_information/distrPS0100_2.csv")
                  , read.csv("~/projecto_staid/poker_information/distrPS0050_2.csv")
  )                          
  distributions <- bootstrap_distributions_2p(subset(PS_all, street==1), reps)
  save(distributions, file=paste(path_poker, "poker_distributions_2p_PS_st1_", increment_me, ".Rdata", sep=''))
  distributions <- bootstrap_distributions_2p(subset(PS_all, street==0), reps)
  save(distributions, file=paste(path_poker, "poker_distributions_2p_PS_st0_", increment_me, ".Rdata", sep=''))
  distributions <- bootstrap_distributions_2p(subset(PS_all, street==2), reps)
  save(distributions, file=paste(path_poker, "poker_distributions_2p_PS_st2_", increment_me, ".Rdata", sep=''))
  distributions <- bootstrap_distributions_2p(subset(PS_all, street==3), reps)
  save(distributions, file=paste(path_poker, "poker_distributions_2p_PS_st3_", increment_me, ".Rdata", sep=''))
  distributions <- bootstrap_distributions_2p(subset(PS_all, street==4), reps)
  save(distributions, file=paste(path_poker, "poker_distributions_2p_PS_st4_", increment_me, ".Rdata", sep=''))
  file_PS_st0 <- paste(path_poker, "poker_distributions_2p_PS_st0_", increment_me, ".Rdata", sep='')
  file_PS_st1 <- paste(path_poker, "poker_distributions_2p_PS_st1_", increment_me, ".Rdata", sep='')
  file_PS_st2 <- paste(path_poker, "poker_distributions_2p_PS_st2_", increment_me, ".Rdata", sep='')
  file_PS_st3 <- paste(path_poker, "poker_distributions_2p_PS_st3_", increment_me, ".Rdata", sep='')
  file_PS_st4 <- paste(path_poker, "poker_distributions_2p_PS_st4_", increment_me, ".Rdata", sep='')
stat_long_2p_st <- rbind(
   cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st0,specific=NA)), street=0,  site="PS", specific=NA)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st1, specific=NA)), street=1,  site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st2, specific=NA)), street=2, site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st3, specific=NA)), street=3,  site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st4, specific=NA)), street=4,  site="PS", specific=NA)
                                )
stat_long_2p_st_spec <- rbind(
  cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st0, specific=1)), street=0,  site="PS", specific=1)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st0, specific=2)), street=0,  site="PS", specific=2)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st0, specific=3)), street=0,  site="PS", specific=3)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st1, specific=1 )), street=1,   site="PS", specific=1)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st1, specific=2 )), street=1,   site="PS", specific=2)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st1, specific=3 )), street=1,   site="PS", specific=3)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st2, specific=1 )), street=2,   site="PS", specific=1)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st2, specific=2 )), street=2,   site="PS", specific=2)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st2, specific=3 )), street=2,   site="PS", specific=3)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st3, specific=1 )), street=3,   site="PS", specific=1) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st3, specific=2 )), street=3,   site="PS", specific=2) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st3, specific=3 )), street=3,   site="PS", specific=3) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st4, specific=1 )), street=4,   site="PS", specific=1) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st4, specific=2 )), street=4,   site="PS", specific=2) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_st4, specific=3 )), street=4,   site="PS", specific=3) 
                                )
street_stat_long <- subset(stat_long_2p_st,  q %in% c("ui1", "ue2", "rdn", "syn") & setting %ni% c("Shark v Shark"))
street_stat_long$q <- factor(as.character(street_stat_long$q), levels=c("ui1", "ue2", "rdn", "syn"), labels=c("Unq(E1;I1)", "Unq(E1;E2)", "Rdn(E1;I1,E2)", "Syn(E1;I1,E2)"))
ggplot(street_stat_long, aes(factor(street), val, group=setting, color=setting) ) + geom_point(position = position_jitter(width = .25)) + stat_summary(fun.y=mean, fun.ymin=function(y) quantile(y, c(0.025)), fun.ymax=function(y) quantile(y, c(0.975)), geom="errorbar", width= 0.5) + facet_wrap( ~ q , ncol=4) + scale_x_discrete("Street")+ scale_y_continuous("Bits") + scale_color_brewer("Match", type="qual", palette=2)
ggplot(subset(stat_long_2p_st_spec, site == "PS" & q %in% c("ui1", "ue2", "rdn", "syn") & setting %ni% c("Shark v Shark") ), aes(factor(street), val, group=setting, color=setting) ) + geom_point() + stat_summary(fun.y=mean, fun.ymin=function(y) quantile(y, c(0.025)), fun.ymax=function(y) quantile(y, c(0.975)), geom="errorbar", width= 0.5) + facet_grid( specific ~ q ) + scale_x_discrete("Blind")+ scale_y_continuous("Bits")

ggplot(street_stat_long, aes(factor(street), val, group=setting, color=setting) ) + geom_point(position = position_jitter(width = .25)) + stat_summary(fun.y=mean, fun.ymin=function(y) quantile(y, c(0.025)), fun.ymax=function(y) quantile(y, c(0.975)), geom="errorbar", width= 0.5) + facet_wrap( ~ q , ncol=4) + scale_x_discrete("Street")+ scale_y_continuous("Bits") + scale_color_brewer("Match", type="qual", palette=2) + theme_few() + theme(aspect.ratio=1)
p <- ggplot(subset(street_stat_long, street != 0), aes(factor(street), val, group=setting, color=setting) ) + geom_point(position = position_jitter(width = .25), size=0.5) + stat_summary(fun.y=mean, fun.ymin=function(y) quantile(y, c(0.025)), fun.ymax=function(y) quantile(y, c(0.975)), geom="errorbar", width= 0.5) + facet_wrap( ~ q , ncol=4) + scale_x_discrete("Street")+ scale_y_continuous("Bits") + scale_color_brewer("Match", type="qual", palette=2) + theme_few() + theme(aspect.ratio=1)
  ggsave( p , filename=paste(path_poker, "info_by_street", increment_me, ".pdf", sep=''), width=8.5, height=2.5, units="in", scale=1.0)
}
