#!/usr/bin/env Rscript
source("~/projecto/research_projects/poker_information/info_decomp_fns003.r")

reps <- 60
increment_me <- "020"

path_poker <- "~/projecto/research_projects/poker_information/"
file_ABS_1000 <- paste(path_poker, "poker_distributions_2p_ABS_1000_", increment_me, ".Rdata", sep='')
file_ABS_0600 <- paste(path_poker, "poker_distributions_2p_ABS_0600_", increment_me, ".Rdata", sep='')
file_ABS_0400 <- paste(path_poker, "poker_distributions_2p_ABS_0400_", increment_me, ".Rdata", sep='')
file_ABS_0200 <- paste(path_poker, "poker_distributions_2p_ABS_0200_", increment_me, ".Rdata", sep='')
file_ABS_0100 <- paste(path_poker, "poker_distributions_2p_ABS_0100_", increment_me, ".Rdata", sep='')
file_ABS_0050 <- paste(path_poker, "poker_distributions_2p_ABS_0050_", increment_me, ".Rdata", sep='')
file_PS_1000 <- paste(path_poker, "poker_distributions_2p_PS_1000_", increment_me, ".Rdata", sep='')
file_PS_0600 <- paste(path_poker, "poker_distributions_2p_PS_0600_", increment_me, ".Rdata", sep='')
file_PS_0400 <- paste(path_poker, "poker_distributions_2p_PS_0400_", increment_me, ".Rdata", sep='')
file_PS_0200 <- paste(path_poker, "poker_distributions_2p_PS_0200_", increment_me, ".Rdata", sep='')
file_PS_0100 <- paste(path_poker, "poker_distributions_2p_PS_0100_", increment_me, ".Rdata", sep='')
file_PS_0050 <- paste(path_poker, "poker_distributions_2p_PS_0050_", increment_me, ".Rdata", sep='')

print("ABS 1000")
bootstrap_distributions_to_file(paste(path_poker, "distrABS100.csv", sep=''), reps, file_ABS_1000)
print("ABS 0600")
bootstrap_distributions_to_file(paste(path_poker, "distrABS060.csv", sep=''), reps, file_ABS_0600)
print("ABS 0400")
bootstrap_distributions_to_file(paste(path_poker, "distrABS040.csv", sep=''), reps, file_ABS_0400)
print("ABS 0200")
bootstrap_distributions_to_file(paste(path_poker, "distrABS020.csv", sep=''), reps, file_ABS_0200)
print("ABS 0100")
bootstrap_distributions_to_file(paste(path_poker, "distrABS010.csv", sep=''), reps, file_ABS_0100)
print("ABS 0050")
bootstrap_distributions_to_file(paste(path_poker, "distrABS005.csv", sep=''), reps, file_ABS_0050)
print("PS 1000")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS1000.csv", reps, file_PS_1000)
print("PS 0600")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS0600.csv", reps, file_PS_0600)
print("PS 0400")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS0400.csv", reps, file_PS_0400)
print("PS 0200")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS0200.csv", reps, file_PS_0200)
print("PS 0100")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS0100.csv", reps, file_PS_0100)
print("PS 0050")
bootstrap_distributions_to_file("~/projecto_staid/poker_information/distrPS0050.csv", reps, file_PS_0050)

print("long form"); Sys.time()
stat_long_2p <- rbind(
  cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_1000,specific=NA)),blind=10.00,ublind="ABS10.00", site="ABS", specific=NA)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0600,specific=NA)),blind=6.00, ublind="ABS6.00", site="ABS", specific=NA)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0400,specific=NA)),blind=4.00, ublind="ABS4.00", site="ABS", specific=NA)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0200,specific=NA)),blind=2.00, ublind="ABS2.00", site="ABS", specific=NA)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0100,specific=NA)),blind=1.00, ublind="ABS1.00", site="ABS", specific=NA)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0050,specific=NA)),blind=0.50, ublind="ABS0.50", site="ABS", specific=NA)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_1000,specific=NA)), blind=10.00, ublind="PS10.00", site="PS", specific=NA)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0600, specific=NA)), blind=6.00, ublind="PS6.00", site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0400, specific=NA)), blind=4.00, ublind="PS4.00", site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0200, specific=NA)), blind=2.00, ublind="PS2.00", site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0100, specific=NA)), blind=1.00, ublind="PS1.00", site="PS", specific=NA)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0050, specific=NA)), blind=0.50, ublind="PS0.50", site="PS", specific=NA)
                                )
stat_long_2p_spec <- rbind(
 cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_1000, specific=1)), blind=10.00, ublind="ABS10.00", site="ABS", specific=1)
 ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_1000,specific=2)), blind=10.00, ublind="ABS10.00", site="ABS", specific=2)
 ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_1000,specific=3)), blind=10.00, ublind="ABS10.00", site="ABS", specific=3)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0600, specific=1)), blind=6.00, ublind="ABS6.00", site="ABS", specific=1)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0600, specific=2)), blind=6.00, ublind="ABS6.00", site="ABS", specific=2)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0600, specific=3)), blind=6.00, ublind="ABS6.00", site="ABS", specific=3)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0400, specific=1)), blind=4.00, ublind="ABS4.00", site="ABS", specific=1)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0400, specific=2)), blind=4.00, ublind="ABS4.00", site="ABS", specific=2)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0400, specific=3)), blind=4.00, ublind="ABS4.00", site="ABS", specific=3)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0200, specific=1)), blind=2.00, ublind="ABS2.00", site="ABS", specific=1)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0200, specific=2)), blind=2.00, ublind="ABS2.00", site="ABS", specific=2)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0200, specific=3)), blind=2.00, ublind="ABS2.00", site="ABS", specific=3)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0100, specific=1)), blind=1.00, ublind="ABS1.00", site="ABS", specific=1)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0100, specific=2)), blind=1.00, ublind="ABS1.00", site="ABS", specific=2)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0100, specific=3)), blind=1.00, ublind="ABS1.00", site="ABS", specific=3)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0050, specific=1)), blind=0.50, ublind="ABS0.50", site="ABS", specific=1)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0050, specific=2)), blind=0.50, ublind="ABS0.50", site="ABS", specific=2)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_ABS_0050, specific=3)), blind=0.50, ublind="ABS0.50", site="ABS", specific=3)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_1000, specific=1)), blind=10.00, ublind="PS10.00", site="PS", specific=1)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_1000, specific=2)), blind=10.00, ublind="PS10.00", site="PS", specific=2)
  ,cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_1000, specific=3)), blind=10.00, ublind="PS10.00", site="PS", specific=3)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0600, specific=1 )), blind=6.00, ublind="PS6.00", site="PS", specific=1)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0600, specific=2 )), blind=6.00, ublind="PS6.00", site="PS", specific=2)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0600, specific=3 )), blind=6.00, ublind="PS6.00", site="PS", specific=3)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0400, specific=1 )), blind=4.00, ublind="PS4.00", site="PS", specific=1)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0400, specific=2 )), blind=4.00, ublind="PS4.00", site="PS", specific=2)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0400, specific=3 )), blind=4.00, ublind="PS4.00", site="PS", specific=3)
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0200, specific=1 )), blind=2.00, ublind="PS2.00", site="PS", specific=1) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0200, specific=2 )), blind=2.00, ublind="PS2.00", site="PS", specific=2) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0200, specific=3 )), blind=2.00, ublind="PS2.00", site="PS", specific=3) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0100, specific=1 )), blind=1.00, ublind="PS1.00", site="PS", specific=1) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0100, specific=2 )), blind=1.00, ublind="PS1.00", site="PS", specific=2) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0100, specific=3 )), blind=1.00, ublind="PS1.00", site="PS", specific=3) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0050, specific=1 )), blind=0.50, ublind="PS0.50", site="PS", specific=1) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0050, specific=2 )), blind=0.50, ublind="PS0.50", site="PS", specific=2) 
  , cbind(build_stat_long_2p(get_statistics_2p_from_file(file_PS_0050, specific=3 )), blind=0.50, ublind="PS0.50", site="PS", specific=3) 
                                )

save(list=c("stat_long_2p", "stat_long_2p_spec"), file=paste("~/projecto/research_projects/poker_information/poker_graph_ready_data_", increment_me, ".Rdata", sep=''))
                                )
